// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEfCwlf49Qcm4k2lKsUYaT-6O7torXQx0',
    appId: '1:428758505239:web:b3de1eb8e6e0bc8cec4952',
    messagingSenderId: '428758505239',
    projectId: 'prayog-1795a',
    authDomain: 'prayog-1795a.firebaseapp.com',
    storageBucket: 'prayog-1795a.firebasestorage.app',
    measurementId: 'G-TCTS2QNF3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7YiocTsB3g3eV-BEgpq95L7dVpBk2Rt0',
    appId: '1:428758505239:android:c5e177663579f59bec4952',
    messagingSenderId: '428758505239',
    projectId: 'prayog-1795a',
    storageBucket: 'prayog-1795a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHRwKz86hvV7QTSaWEEXKDDBqx5Kt8tm8',
    appId: '1:428758505239:ios:c4596ee9d7c98e9bec4952',
    messagingSenderId: '428758505239',
    projectId: 'prayog-1795a',
    storageBucket: 'prayog-1795a.firebasestorage.app',
    iosBundleId: 'com.example.kailasha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHRwKz86hvV7QTSaWEEXKDDBqx5Kt8tm8',
    appId: '1:428758505239:ios:c4596ee9d7c98e9bec4952',
    messagingSenderId: '428758505239',
    projectId: 'prayog-1795a',
    storageBucket: 'prayog-1795a.firebasestorage.app',
    iosBundleId: 'com.example.kailasha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEfCwlf49Qcm4k2lKsUYaT-6O7torXQx0',
    appId: '1:428758505239:web:120dbd11bbf5baa8ec4952',
    messagingSenderId: '428758505239',
    projectId: 'prayog-1795a',
    authDomain: 'prayog-1795a.firebaseapp.com',
    storageBucket: 'prayog-1795a.firebasestorage.app',
    measurementId: 'G-D1CL27QS8M',
  );
}
